declare const _default: FetchMock;
export default _default;
export type RouteMatcher = import("./Router").RouteMatcher;
export type RouteName = import("./Route").RouteName;
export type UserRouteConfig = import("./Route").UserRouteConfig;
export type RouteResponse = import("./Router").RouteResponse;
export type MatcherDefinition = import("./Matchers").MatcherDefinition;
export type CallLog = import("./CallHistory").CallLog;
export type RouteResponseFunction = import("./Route").RouteResponseFunction;
export type FetchMockConfig = {
    sendAsJson?: boolean;
    includeContentLength?: boolean;
    warnOnFallback?: boolean;
    matchPartialBody?: boolean;
    fetch?: (arg0: string | Request, arg1: RequestInit) => Promise<Response>;
    Headers?: typeof Headers;
    Request?: typeof Request;
    Response?: typeof Response;
};
export type FetchMockCore = {
    config: FetchMockConfig;
    router: Router;
    callHistory: CallHistory;
    createInstance: () => FetchMock;
    fetchHandler: (arg0: string | Request, arg1: RequestInit) => Promise<Response>;
    route: (arg0: any, arg1: any, arg2: any) => FetchMock;
    catch: (arg0: RouteResponse | undefined) => FetchMock;
    defineMatcher: (arg0: MatcherDefinition) => void;
    removeRoutes: (arg0: object) => void;
    clearHistory: () => void;
};
export type AdditionalRouteMethodName = "get" | "post" | "put" | "delete" | "head" | "patch" | "once" | "sticky" | "any" | "anyOnce" | "getOnce" | "postOnce" | "putOnce" | "deleteOnce" | "headOnce" | "patchOnce" | "getAny" | "postAny" | "putAny" | "deleteAny" | "headAny" | "patchAny" | "getAnyOnce" | "postAnyOnce" | "putAnyOnce" | "deleteAnyOnce" | "headAnyOnce" | "patchAnyOnce";
export type AdditionalRouteMethods = {
    get: (arg0: RouteMatcher | UserRouteConfig, arg1: RouteResponse, arg2: UserRouteConfig | RouteName) => FetchMock;
    post: (arg0: RouteMatcher | UserRouteConfig, arg1: RouteResponse, arg2: UserRouteConfig | RouteName) => FetchMock;
    put: (arg0: RouteMatcher | UserRouteConfig, arg1: RouteResponse, arg2: UserRouteConfig | RouteName) => FetchMock;
    delete: (arg0: RouteMatcher | UserRouteConfig, arg1: RouteResponse, arg2: UserRouteConfig | RouteName) => FetchMock;
    head: (arg0: RouteMatcher | UserRouteConfig, arg1: RouteResponse, arg2: UserRouteConfig | RouteName) => FetchMock;
    patch: (arg0: RouteMatcher | UserRouteConfig, arg1: RouteResponse, arg2: UserRouteConfig | RouteName) => FetchMock;
    once: (arg0: RouteMatcher | UserRouteConfig, arg1: RouteResponse, arg2: UserRouteConfig | RouteName) => FetchMock;
    sticky: (arg0: RouteMatcher | UserRouteConfig, arg1: RouteResponse, arg2: UserRouteConfig | RouteName) => FetchMock;
    getOnce: (arg0: RouteMatcher | UserRouteConfig, arg1: RouteResponse, arg2: UserRouteConfig | RouteName) => FetchMock;
    postOnce: (arg0: RouteMatcher | UserRouteConfig, arg1: RouteResponse, arg2: UserRouteConfig | RouteName) => FetchMock;
    putOnce: (arg0: RouteMatcher | UserRouteConfig, arg1: RouteResponse, arg2: UserRouteConfig | RouteName) => FetchMock;
    deleteOnce: (arg0: RouteMatcher | UserRouteConfig, arg1: RouteResponse, arg2: UserRouteConfig | RouteName) => FetchMock;
    headOnce: (arg0: RouteMatcher | UserRouteConfig, arg1: RouteResponse, arg2: UserRouteConfig | RouteName) => FetchMock;
    patchOnce: (arg0: RouteMatcher | UserRouteConfig, arg1: RouteResponse, arg2: UserRouteConfig | RouteName) => FetchMock;
    any: (arg0: RouteResponse, arg1: UserRouteConfig | RouteName) => FetchMock;
    anyOnce: (arg0: RouteResponse, arg1: UserRouteConfig | RouteName) => FetchMock;
    getAny: (arg0: RouteResponse, arg1: UserRouteConfig | RouteName) => FetchMock;
    postAny: (arg0: RouteResponse, arg1: UserRouteConfig | RouteName) => FetchMock;
    putAny: (arg0: RouteResponse, arg1: UserRouteConfig | RouteName) => FetchMock;
    deleteAny: (arg0: RouteResponse, arg1: UserRouteConfig | RouteName) => FetchMock;
    headAny: (arg0: RouteResponse, arg1: UserRouteConfig | RouteName) => FetchMock;
    patchAny: (arg0: RouteResponse, arg1: UserRouteConfig | RouteName) => FetchMock;
    getAnyOnce: (arg0: RouteResponse, arg1: UserRouteConfig | RouteName) => FetchMock;
    postAnyOnce: (arg0: RouteResponse, arg1: UserRouteConfig | RouteName) => FetchMock;
    putAnyOnce: (arg0: RouteResponse, arg1: UserRouteConfig | RouteName) => FetchMock;
    deleteAnyOnce: (arg0: RouteResponse, arg1: UserRouteConfig | RouteName) => FetchMock;
    headAnyOnce: (arg0: RouteResponse, arg1: UserRouteConfig | RouteName) => FetchMock;
    patchAnyOnce: (arg0: RouteResponse, arg1: UserRouteConfig | RouteName) => FetchMock;
};
export type FetchMock = FetchMockCore & AdditionalRouteMethods;
import Router from './Router.js';
import CallHistory from './CallHistory.js';
